---
# tasks file for roles/nginx
- name: Asegurar que Nginx esté instalado
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Configurar archivo de Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: "0644"
  notify: reiniciar nginx

- name: Asegurar que Nginx esté habilitado y corriendo
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
