---
# tasks file for roles/firewall
- name: Validar estado Servicio de Firewall
  ansible.builtin.dnf:
    name:
      - firewalld
    state: present

- name: Asegurar que el servicio este habilitado y en funcionamiento
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Permitir trafico HTTPS Por el FW
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true
