---
# tasks file for roles/security
- name: Actualizar todos los paquetes a su última versión estable
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true

- name: Instalar repo epel-release
  ansible.builtin.dnf:
    name:
      - epel-release
    state: present
  when: ansible_distribution == 'Rocky'

- name: Instalar herramientas de seguridad básicas
  ansible.builtin.yum:
    name:
      - fail2ban
      - firewalld
    state: present

# Asegurar que fail2ban esté habilitado y corriendo
- name: Asegurar que fail2ban esté habilitado y en funcionamiento
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

# Configurar firewalld
- name: Asegurar que firewalld esté habilitado y en funcionamiento
  block:
    - name: Habilitar e Inicializar Firewall
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Abrir puertos HTTP y HTTPS en firewalld
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 80/tcp
        - 443/tcp
