---
# tasks file for roles/users
- name: Crear grupos necesarios para usuarios web
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ users_system_groups }}"

- name: Crear usuarios para la gestión del servidor web
  ansible.builtin.user:
    name: "{{ item.nombre }}"
    comment: "{{ item.comentario }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.grupos | join(',') }}"
    password: "{{ item.password_hash }}"
    state: present
  loop: "{{ users_usuarios_web }}"
